services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_DB: iot_data_db
      POSTGRES_USER: iot_db_user
      POSTGRES_PASSWORD: a1b2c3d4
    ports:
      - "5433:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data
    networks:
      - red-backend-app

  receiver-iot-service:
    image: 'alvarosalazar/receiver-iot:latest'
    ports:
      - '8080:8080'
    depends_on:
      - timescaledb
    environment:
      DB_URL: jdbc:postgresql://timescaledb/iot_data_db
      DB_USERNAME: iot_db_user
      DB_PASSWORD: a1b2c3d4
      JPA_DDL: create-drop
      MQTT_BROKER: ssl://mqtt-iot.freeddns.org:8883
      MQTT_CLIENTID: receiver
      MQTT_USERNAME: admin
      MQTT_PASSWORD: admin1234
      MQTT_TOPIC: +/+/+/+/+/+
      MQTT_QOS: 0
    profiles:
      - app
    networks:
      - red-backend-app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on: 
      - timescaledb
    restart: unless-stopped
    networks:
      - red-backend-app


volumes:
  timescale-data:
  grafana-storage:


networks:
  red-backend-app:
    driver: bridge
